on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: checkout
      uses: actions/checkout@master

    - name: "Build frontend"
      uses: okteto/build@latest
      with:
        tag: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }}
        path: frontend
        file: frontend/Dockerfile

    - name: "Build api"
      uses: okteto/build@latest
      with:
        tag: ${{ secrets.DOCKER_HUB_USERNAME }}/api:${{ github.sha }}
        path: api
        file: api/Dockerfile
